<?php require_once("config.php"); ?>
<?php require_once("city.php"); ?>
<?php require_once("database.php"); ?>
<?php require_once("db_object.php"); ?>
<?php require_once("division.php"); ?>
<?php require_once("place.php"); ?>
<?php require_once("plan.php"); ?>
<?php require_once("register.php"); ?>
<?php require_once("user.php"); ?>
<?php require_once("registerHotel.php"); ?>
<?php require_once("profilecls.php"); ?>
<?php require_once("admin.php"); ?>
<?php require_once("adminpro.php"); ?>
<?php require_once("booking.php"); ?>
<?php require_once("session.php"); ?>
<?php require_once("blog.php"); ?>
<?php require_once("BlogComment.php"); ?>
<?php require_once("BlogLike.php"); ?>
